version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
    redisinsight:
        image: redislabs/redisinsight:latest
        container_name: redis-insight
        ports:
            - 8001:8001
        volumes:
            - ./redisinsight:/db
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/init.sh
            - dbdata:/data/db
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - '8081:8081'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_AUTH_USERNAME=user
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=secret
        depends_on:
            - mongo
volumes:
    dbdata:
